name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '43 7 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Looks like there has not been activity on this issue for a while. Marking as stale.'
        stale-pr-message: 'Looks like there has not been activity on this PR for a while. Marking as stale.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
